name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Adjust this based on your project's build script

    - name: Deploy
      # Here I am supposed to typically deploy this application to a server.
      # But For demonstration purposes, I'll just print a deploy message.
      run: echo "Deploying the application..."
